// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230917021541_Servico")]
    partial class Servico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.CategoriaServicoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_update");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_create");

                    b.HasKey("Id");

                    b.ToTable("service_category");
                });

            modelBuilder.Entity("Api.Domain.Entities.ServicoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaServicoEntityId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_servico_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("DuracaoHoras")
                        .HasColumnType("int")
                        .HasColumnName("duration_hours");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_update");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_create");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaServicoEntityId");

                    b.ToTable("service");
                });

            modelBuilder.Entity("Api.Domain.Entities.TipoPagamentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<double>("JurosPorcentagem")
                        .HasColumnType("double")
                        .HasColumnName("interest_percentage");

                    b.Property<int>("QrtParcelas")
                        .HasColumnType("int")
                        .HasColumnName("installments_number");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_update");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("longtext")
                        .HasColumnName("user_create");

                    b.HasKey("Id");

                    b.ToTable("payment_type");
                });

            modelBuilder.Entity("Api.Domain.Entities.ServicoEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.CategoriaServicoEntity", "CategoriaServicoEntity")
                        .WithMany()
                        .HasForeignKey("CategoriaServicoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaServicoEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
